/********************************************************************************
** Form generated from reading UI file 'positionseriate.ui'
**
** Created by: Qt User Interface Compiler version 4.8.7
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_POSITIONSERIATE_H
#define UI_POSITIONSERIATE_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QComboBox>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QLineEdit>
#include <QtGui/QPushButton>
#include <QtGui/QStackedWidget>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_PositionSeriate
{
public:
    QLabel *label;
    QLineEdit *lineEdit_posi_variable;
    QPushButton *pushButton_posi_variate_data;
    QLabel *label_2;
    QLabel *label_3;
    QComboBox *comboBox_po_co_select;
    QStackedWidget *stackedWidget;
    QWidget *page;
    QLabel *label_4;
    QLineEdit *lineEdit_posS_Sjj1;
    QLabel *label_5;
    QLineEdit *lineEdit_posS_Sjj2;
    QLabel *label_6;
    QLabel *label_7;
    QLineEdit *lineEdit_posS_Sjj4;
    QLineEdit *lineEdit_posS_Sjj3;
    QLabel *label_8;
    QLabel *label_9;
    QLabel *label_10;
    QLabel *label_11;
    QLineEdit *lineEdit_posS_Sjj6;
    QLineEdit *lineEdit_posS_Sjj5;
    QLabel *label_12;
    QLabel *label_13;
    QLabel *label_14;
    QLabel *label_15;
    QLineEdit *lineEdit_posS_Sjj8;
    QLineEdit *lineEdit_posS_Sjj7;
    QLabel *label_16;
    QLabel *label_17;
    QLabel *label_18;
    QLabel *label_19;
    QWidget *page_2;
    QLabel *label_38;
    QLabel *label_39;
    QLineEdit *lineEdit_18;
    QLabel *label_40;
    QLabel *label_41;
    QLabel *label_42;
    QLineEdit *lineEdit_19;
    QLabel *label_43;
    QLabel *label_44;
    QLabel *label_45;
    QLabel *label_46;
    QLineEdit *lineEdit_20;
    QLabel *label_47;
    QLabel *label_48;
    QLineEdit *lineEdit_21;
    QLabel *label_49;
    QLabel *label_50;
    QLineEdit *lineEdit_22;
    QLineEdit *lineEdit_23;
    QLineEdit *lineEdit_24;
    QLineEdit *lineEdit_25;
    QLabel *label_51;
    QLabel *label_52;
    QLabel *label_53;
    QLabel *label_20;
    QLabel *label_21;
    QComboBox *comboBox_cu_co_select;
    QPushButton *pushButton_pos_save;
    QPushButton *pushButton_pos_close;
    QStackedWidget *stackedWidget_2;
    QWidget *page_3;
    QLabel *label_22;
    QLineEdit *lineEdit_posC_j1;
    QLabel *label_23;
    QLineEdit *lineEdit_posC_j2;
    QLabel *label_24;
    QLabel *label_25;
    QLineEdit *lineEdit_posC_j4;
    QLineEdit *lineEdit_posC_j3;
    QLabel *label_26;
    QLabel *label_27;
    QLabel *label_28;
    QLabel *label_29;
    QLineEdit *lineEdit_posC_j6;
    QLineEdit *lineEdit_posC_j5;
    QLabel *label_30;
    QLabel *label_31;
    QLabel *label_32;
    QLabel *label_33;
    QLineEdit *lineEdit_posC_j8;
    QLineEdit *lineEdit_posC_j7;
    QLabel *label_34;
    QLabel *label_35;
    QLabel *label_36;
    QLabel *label_37;
    QWidget *page_4;
    QLabel *label_54;
    QLabel *label_55;
    QLineEdit *lineEdit_26;
    QLabel *label_56;
    QLabel *label_57;
    QLabel *label_58;
    QLineEdit *lineEdit_posS_X;
    QLabel *label_59;
    QLabel *label_60;
    QLabel *label_61;
    QLabel *label_62;
    QLineEdit *lineEdit_posS_Y;
    QLabel *label_63;
    QLabel *label_64;
    QLineEdit *lineEdit_posS_A;
    QLabel *label_65;
    QLabel *label_66;
    QLineEdit *lineEdit_posS_C;
    QLineEdit *lineEdit_posS_Z;
    QLineEdit *lineEdit_32;
    QLineEdit *lineEdit_posS_B;
    QLabel *label_67;
    QLabel *label_68;
    QLabel *label_69;
    QPushButton *pushButton_setpu_currentposition;
    QPushButton *pushButton_new_position;
    QPushButton *pushButton_select_position;

    void setupUi(QWidget *PositionSeriate)
    {
        if (PositionSeriate->objectName().isEmpty())
            PositionSeriate->setObjectName(QString::fromUtf8("PositionSeriate"));
        PositionSeriate->resize(600, 493);
        label = new QLabel(PositionSeriate);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(20, 40, 151, 21));
        QFont font;
        font.setPointSize(9);
        font.setItalic(true);
        label->setFont(font);
        lineEdit_posi_variable = new QLineEdit(PositionSeriate);
        lineEdit_posi_variable->setObjectName(QString::fromUtf8("lineEdit_posi_variable"));
        lineEdit_posi_variable->setGeometry(QRect(170, 36, 113, 31));
        pushButton_posi_variate_data = new QPushButton(PositionSeriate);
        pushButton_posi_variate_data->setObjectName(QString::fromUtf8("pushButton_posi_variate_data"));
        pushButton_posi_variate_data->setGeometry(QRect(290, 40, 99, 27));
        pushButton_posi_variate_data->setFont(font);
        label_2 = new QLabel(PositionSeriate);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(30, 100, 91, 21));
        label_2->setFont(font);
        label_3 = new QLabel(PositionSeriate);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(30, 130, 61, 17));
        label_3->setFont(font);
        comboBox_po_co_select = new QComboBox(PositionSeriate);
        comboBox_po_co_select->setObjectName(QString::fromUtf8("comboBox_po_co_select"));
        comboBox_po_co_select->setGeometry(QRect(110, 120, 111, 31));
        comboBox_po_co_select->setFont(font);
        stackedWidget = new QStackedWidget(PositionSeriate);
        stackedWidget->setObjectName(QString::fromUtf8("stackedWidget"));
        stackedWidget->setGeometry(QRect(20, 150, 221, 271));
        page = new QWidget();
        page->setObjectName(QString::fromUtf8("page"));
        label_4 = new QLabel(page);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(10, 20, 51, 31));
        label_4->setFrameShape(QFrame::StyledPanel);
        lineEdit_posS_Sjj1 = new QLineEdit(page);
        lineEdit_posS_Sjj1->setObjectName(QString::fromUtf8("lineEdit_posS_Sjj1"));
        lineEdit_posS_Sjj1->setGeometry(QRect(60, 20, 101, 31));
        label_5 = new QLabel(page);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(160, 20, 51, 31));
        label_5->setFrameShape(QFrame::StyledPanel);
        lineEdit_posS_Sjj2 = new QLineEdit(page);
        lineEdit_posS_Sjj2->setObjectName(QString::fromUtf8("lineEdit_posS_Sjj2"));
        lineEdit_posS_Sjj2->setGeometry(QRect(60, 50, 101, 31));
        label_6 = new QLabel(page);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(160, 50, 51, 31));
        label_6->setFrameShape(QFrame::StyledPanel);
        label_7 = new QLabel(page);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(10, 50, 51, 31));
        label_7->setFrameShape(QFrame::StyledPanel);
        lineEdit_posS_Sjj4 = new QLineEdit(page);
        lineEdit_posS_Sjj4->setObjectName(QString::fromUtf8("lineEdit_posS_Sjj4"));
        lineEdit_posS_Sjj4->setGeometry(QRect(60, 110, 101, 31));
        lineEdit_posS_Sjj3 = new QLineEdit(page);
        lineEdit_posS_Sjj3->setObjectName(QString::fromUtf8("lineEdit_posS_Sjj3"));
        lineEdit_posS_Sjj3->setGeometry(QRect(60, 80, 101, 31));
        label_8 = new QLabel(page);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(10, 110, 51, 31));
        label_8->setFrameShape(QFrame::StyledPanel);
        label_9 = new QLabel(page);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(160, 80, 51, 31));
        label_9->setFrameShape(QFrame::StyledPanel);
        label_10 = new QLabel(page);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(10, 80, 51, 31));
        label_10->setFrameShape(QFrame::StyledPanel);
        label_11 = new QLabel(page);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(160, 110, 51, 31));
        label_11->setFrameShape(QFrame::StyledPanel);
        lineEdit_posS_Sjj6 = new QLineEdit(page);
        lineEdit_posS_Sjj6->setObjectName(QString::fromUtf8("lineEdit_posS_Sjj6"));
        lineEdit_posS_Sjj6->setGeometry(QRect(60, 170, 101, 31));
        lineEdit_posS_Sjj5 = new QLineEdit(page);
        lineEdit_posS_Sjj5->setObjectName(QString::fromUtf8("lineEdit_posS_Sjj5"));
        lineEdit_posS_Sjj5->setGeometry(QRect(60, 140, 101, 31));
        label_12 = new QLabel(page);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(10, 170, 51, 31));
        label_12->setFrameShape(QFrame::StyledPanel);
        label_13 = new QLabel(page);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(160, 140, 51, 31));
        label_13->setFrameShape(QFrame::StyledPanel);
        label_14 = new QLabel(page);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(10, 140, 51, 31));
        label_14->setFrameShape(QFrame::StyledPanel);
        label_15 = new QLabel(page);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(160, 170, 51, 31));
        label_15->setFrameShape(QFrame::StyledPanel);
        lineEdit_posS_Sjj8 = new QLineEdit(page);
        lineEdit_posS_Sjj8->setObjectName(QString::fromUtf8("lineEdit_posS_Sjj8"));
        lineEdit_posS_Sjj8->setGeometry(QRect(60, 230, 101, 31));
        lineEdit_posS_Sjj7 = new QLineEdit(page);
        lineEdit_posS_Sjj7->setObjectName(QString::fromUtf8("lineEdit_posS_Sjj7"));
        lineEdit_posS_Sjj7->setGeometry(QRect(60, 200, 101, 31));
        label_16 = new QLabel(page);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(10, 230, 51, 31));
        label_16->setFrameShape(QFrame::StyledPanel);
        label_17 = new QLabel(page);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(160, 200, 51, 31));
        label_17->setFrameShape(QFrame::StyledPanel);
        label_18 = new QLabel(page);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(10, 200, 51, 31));
        label_18->setFrameShape(QFrame::StyledPanel);
        label_19 = new QLabel(page);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(160, 230, 51, 31));
        label_19->setFrameShape(QFrame::StyledPanel);
        stackedWidget->addWidget(page);
        page_2 = new QWidget();
        page_2->setObjectName(QString::fromUtf8("page_2"));
        label_38 = new QLabel(page_2);
        label_38->setObjectName(QString::fromUtf8("label_38"));
        label_38->setGeometry(QRect(10, 80, 51, 31));
        label_38->setFrameShape(QFrame::StyledPanel);
        label_39 = new QLabel(page_2);
        label_39->setObjectName(QString::fromUtf8("label_39"));
        label_39->setGeometry(QRect(160, 200, 51, 31));
        label_39->setFrameShape(QFrame::StyledPanel);
        lineEdit_18 = new QLineEdit(page_2);
        lineEdit_18->setObjectName(QString::fromUtf8("lineEdit_18"));
        lineEdit_18->setGeometry(QRect(60, 200, 101, 31));
        label_40 = new QLabel(page_2);
        label_40->setObjectName(QString::fromUtf8("label_40"));
        label_40->setGeometry(QRect(160, 170, 51, 31));
        label_40->setFrameShape(QFrame::StyledPanel);
        label_41 = new QLabel(page_2);
        label_41->setObjectName(QString::fromUtf8("label_41"));
        label_41->setGeometry(QRect(10, 230, 51, 31));
        label_41->setFrameShape(QFrame::StyledPanel);
        label_42 = new QLabel(page_2);
        label_42->setObjectName(QString::fromUtf8("label_42"));
        label_42->setGeometry(QRect(10, 110, 51, 31));
        label_42->setFrameShape(QFrame::StyledPanel);
        lineEdit_19 = new QLineEdit(page_2);
        lineEdit_19->setObjectName(QString::fromUtf8("lineEdit_19"));
        lineEdit_19->setGeometry(QRect(60, 20, 101, 31));
        label_43 = new QLabel(page_2);
        label_43->setObjectName(QString::fromUtf8("label_43"));
        label_43->setGeometry(QRect(160, 50, 51, 31));
        label_43->setFrameShape(QFrame::StyledPanel);
        label_44 = new QLabel(page_2);
        label_44->setObjectName(QString::fromUtf8("label_44"));
        label_44->setGeometry(QRect(160, 110, 51, 31));
        label_44->setFrameShape(QFrame::StyledPanel);
        label_45 = new QLabel(page_2);
        label_45->setObjectName(QString::fromUtf8("label_45"));
        label_45->setGeometry(QRect(160, 80, 51, 31));
        label_45->setFrameShape(QFrame::StyledPanel);
        label_46 = new QLabel(page_2);
        label_46->setObjectName(QString::fromUtf8("label_46"));
        label_46->setGeometry(QRect(160, 230, 51, 31));
        label_46->setFrameShape(QFrame::StyledPanel);
        lineEdit_20 = new QLineEdit(page_2);
        lineEdit_20->setObjectName(QString::fromUtf8("lineEdit_20"));
        lineEdit_20->setGeometry(QRect(60, 50, 101, 31));
        label_47 = new QLabel(page_2);
        label_47->setObjectName(QString::fromUtf8("label_47"));
        label_47->setGeometry(QRect(160, 20, 51, 31));
        label_47->setFrameShape(QFrame::StyledPanel);
        label_48 = new QLabel(page_2);
        label_48->setObjectName(QString::fromUtf8("label_48"));
        label_48->setGeometry(QRect(10, 20, 51, 31));
        label_48->setFrameShape(QFrame::StyledPanel);
        lineEdit_21 = new QLineEdit(page_2);
        lineEdit_21->setObjectName(QString::fromUtf8("lineEdit_21"));
        lineEdit_21->setGeometry(QRect(60, 110, 101, 31));
        label_49 = new QLabel(page_2);
        label_49->setObjectName(QString::fromUtf8("label_49"));
        label_49->setGeometry(QRect(10, 50, 51, 31));
        label_49->setFrameShape(QFrame::StyledPanel);
        label_50 = new QLabel(page_2);
        label_50->setObjectName(QString::fromUtf8("label_50"));
        label_50->setGeometry(QRect(10, 170, 51, 31));
        label_50->setFrameShape(QFrame::StyledPanel);
        lineEdit_22 = new QLineEdit(page_2);
        lineEdit_22->setObjectName(QString::fromUtf8("lineEdit_22"));
        lineEdit_22->setGeometry(QRect(60, 170, 101, 31));
        lineEdit_23 = new QLineEdit(page_2);
        lineEdit_23->setObjectName(QString::fromUtf8("lineEdit_23"));
        lineEdit_23->setGeometry(QRect(60, 80, 101, 31));
        lineEdit_24 = new QLineEdit(page_2);
        lineEdit_24->setObjectName(QString::fromUtf8("lineEdit_24"));
        lineEdit_24->setGeometry(QRect(60, 230, 101, 31));
        lineEdit_25 = new QLineEdit(page_2);
        lineEdit_25->setObjectName(QString::fromUtf8("lineEdit_25"));
        lineEdit_25->setGeometry(QRect(60, 140, 101, 31));
        label_51 = new QLabel(page_2);
        label_51->setObjectName(QString::fromUtf8("label_51"));
        label_51->setGeometry(QRect(10, 200, 51, 31));
        label_51->setFrameShape(QFrame::StyledPanel);
        label_52 = new QLabel(page_2);
        label_52->setObjectName(QString::fromUtf8("label_52"));
        label_52->setGeometry(QRect(10, 140, 51, 31));
        label_52->setFrameShape(QFrame::StyledPanel);
        label_53 = new QLabel(page_2);
        label_53->setObjectName(QString::fromUtf8("label_53"));
        label_53->setGeometry(QRect(160, 140, 51, 31));
        label_53->setFrameShape(QFrame::StyledPanel);
        stackedWidget->addWidget(page_2);
        label_20 = new QLabel(PositionSeriate);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(290, 130, 61, 17));
        label_20->setFont(font);
        label_21 = new QLabel(PositionSeriate);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(290, 100, 121, 21));
        label_21->setFont(font);
        comboBox_cu_co_select = new QComboBox(PositionSeriate);
        comboBox_cu_co_select->setObjectName(QString::fromUtf8("comboBox_cu_co_select"));
        comboBox_cu_co_select->setGeometry(QRect(380, 120, 111, 31));
        comboBox_cu_co_select->setFont(font);
        pushButton_pos_save = new QPushButton(PositionSeriate);
        pushButton_pos_save->setObjectName(QString::fromUtf8("pushButton_pos_save"));
        pushButton_pos_save->setGeometry(QRect(330, 450, 61, 27));
        QFont font1;
        font1.setPointSize(9);
        pushButton_pos_save->setFont(font1);
        pushButton_pos_close = new QPushButton(PositionSeriate);
        pushButton_pos_close->setObjectName(QString::fromUtf8("pushButton_pos_close"));
        pushButton_pos_close->setGeometry(QRect(410, 450, 61, 27));
        pushButton_pos_close->setFont(font1);
        stackedWidget_2 = new QStackedWidget(PositionSeriate);
        stackedWidget_2->setObjectName(QString::fromUtf8("stackedWidget_2"));
        stackedWidget_2->setGeometry(QRect(280, 150, 221, 271));
        page_3 = new QWidget();
        page_3->setObjectName(QString::fromUtf8("page_3"));
        label_22 = new QLabel(page_3);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(10, 20, 51, 31));
        label_22->setFrameShape(QFrame::StyledPanel);
        lineEdit_posC_j1 = new QLineEdit(page_3);
        lineEdit_posC_j1->setObjectName(QString::fromUtf8("lineEdit_posC_j1"));
        lineEdit_posC_j1->setGeometry(QRect(60, 20, 101, 31));
        label_23 = new QLabel(page_3);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(160, 20, 51, 31));
        label_23->setFrameShape(QFrame::StyledPanel);
        lineEdit_posC_j2 = new QLineEdit(page_3);
        lineEdit_posC_j2->setObjectName(QString::fromUtf8("lineEdit_posC_j2"));
        lineEdit_posC_j2->setGeometry(QRect(60, 50, 101, 31));
        label_24 = new QLabel(page_3);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(160, 50, 51, 31));
        label_24->setFrameShape(QFrame::StyledPanel);
        label_25 = new QLabel(page_3);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(10, 50, 51, 31));
        label_25->setFrameShape(QFrame::StyledPanel);
        lineEdit_posC_j4 = new QLineEdit(page_3);
        lineEdit_posC_j4->setObjectName(QString::fromUtf8("lineEdit_posC_j4"));
        lineEdit_posC_j4->setGeometry(QRect(60, 110, 101, 31));
        lineEdit_posC_j3 = new QLineEdit(page_3);
        lineEdit_posC_j3->setObjectName(QString::fromUtf8("lineEdit_posC_j3"));
        lineEdit_posC_j3->setGeometry(QRect(60, 80, 101, 31));
        label_26 = new QLabel(page_3);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(10, 110, 51, 31));
        label_26->setFrameShape(QFrame::StyledPanel);
        label_27 = new QLabel(page_3);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(160, 80, 51, 31));
        label_27->setFrameShape(QFrame::StyledPanel);
        label_28 = new QLabel(page_3);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(10, 80, 51, 31));
        label_28->setFrameShape(QFrame::StyledPanel);
        label_29 = new QLabel(page_3);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(160, 110, 51, 31));
        label_29->setFrameShape(QFrame::StyledPanel);
        lineEdit_posC_j6 = new QLineEdit(page_3);
        lineEdit_posC_j6->setObjectName(QString::fromUtf8("lineEdit_posC_j6"));
        lineEdit_posC_j6->setGeometry(QRect(60, 170, 101, 31));
        lineEdit_posC_j5 = new QLineEdit(page_3);
        lineEdit_posC_j5->setObjectName(QString::fromUtf8("lineEdit_posC_j5"));
        lineEdit_posC_j5->setGeometry(QRect(60, 140, 101, 31));
        label_30 = new QLabel(page_3);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(10, 170, 51, 31));
        label_30->setFrameShape(QFrame::StyledPanel);
        label_31 = new QLabel(page_3);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(160, 140, 51, 31));
        label_31->setFrameShape(QFrame::StyledPanel);
        label_32 = new QLabel(page_3);
        label_32->setObjectName(QString::fromUtf8("label_32"));
        label_32->setGeometry(QRect(10, 140, 51, 31));
        label_32->setFrameShape(QFrame::StyledPanel);
        label_33 = new QLabel(page_3);
        label_33->setObjectName(QString::fromUtf8("label_33"));
        label_33->setGeometry(QRect(160, 170, 51, 31));
        label_33->setFrameShape(QFrame::StyledPanel);
        lineEdit_posC_j8 = new QLineEdit(page_3);
        lineEdit_posC_j8->setObjectName(QString::fromUtf8("lineEdit_posC_j8"));
        lineEdit_posC_j8->setGeometry(QRect(60, 230, 101, 31));
        lineEdit_posC_j7 = new QLineEdit(page_3);
        lineEdit_posC_j7->setObjectName(QString::fromUtf8("lineEdit_posC_j7"));
        lineEdit_posC_j7->setGeometry(QRect(60, 200, 101, 31));
        label_34 = new QLabel(page_3);
        label_34->setObjectName(QString::fromUtf8("label_34"));
        label_34->setGeometry(QRect(10, 230, 51, 31));
        label_34->setFrameShape(QFrame::StyledPanel);
        label_35 = new QLabel(page_3);
        label_35->setObjectName(QString::fromUtf8("label_35"));
        label_35->setGeometry(QRect(160, 200, 51, 31));
        label_35->setFrameShape(QFrame::StyledPanel);
        label_36 = new QLabel(page_3);
        label_36->setObjectName(QString::fromUtf8("label_36"));
        label_36->setGeometry(QRect(10, 200, 51, 31));
        label_36->setFrameShape(QFrame::StyledPanel);
        label_37 = new QLabel(page_3);
        label_37->setObjectName(QString::fromUtf8("label_37"));
        label_37->setGeometry(QRect(160, 230, 51, 31));
        label_37->setFrameShape(QFrame::StyledPanel);
        stackedWidget_2->addWidget(page_3);
        page_4 = new QWidget();
        page_4->setObjectName(QString::fromUtf8("page_4"));
        label_54 = new QLabel(page_4);
        label_54->setObjectName(QString::fromUtf8("label_54"));
        label_54->setGeometry(QRect(10, 80, 51, 31));
        label_54->setFrameShape(QFrame::StyledPanel);
        label_55 = new QLabel(page_4);
        label_55->setObjectName(QString::fromUtf8("label_55"));
        label_55->setGeometry(QRect(160, 200, 51, 31));
        label_55->setFrameShape(QFrame::StyledPanel);
        lineEdit_26 = new QLineEdit(page_4);
        lineEdit_26->setObjectName(QString::fromUtf8("lineEdit_26"));
        lineEdit_26->setGeometry(QRect(60, 200, 101, 31));
        label_56 = new QLabel(page_4);
        label_56->setObjectName(QString::fromUtf8("label_56"));
        label_56->setGeometry(QRect(160, 170, 51, 31));
        label_56->setFrameShape(QFrame::StyledPanel);
        label_57 = new QLabel(page_4);
        label_57->setObjectName(QString::fromUtf8("label_57"));
        label_57->setGeometry(QRect(10, 230, 51, 31));
        label_57->setFrameShape(QFrame::StyledPanel);
        label_58 = new QLabel(page_4);
        label_58->setObjectName(QString::fromUtf8("label_58"));
        label_58->setGeometry(QRect(10, 110, 51, 31));
        label_58->setFrameShape(QFrame::StyledPanel);
        lineEdit_posS_X = new QLineEdit(page_4);
        lineEdit_posS_X->setObjectName(QString::fromUtf8("lineEdit_posS_X"));
        lineEdit_posS_X->setGeometry(QRect(60, 20, 101, 31));
        label_59 = new QLabel(page_4);
        label_59->setObjectName(QString::fromUtf8("label_59"));
        label_59->setGeometry(QRect(160, 50, 51, 31));
        label_59->setFrameShape(QFrame::StyledPanel);
        label_60 = new QLabel(page_4);
        label_60->setObjectName(QString::fromUtf8("label_60"));
        label_60->setGeometry(QRect(160, 110, 51, 31));
        label_60->setFrameShape(QFrame::StyledPanel);
        label_61 = new QLabel(page_4);
        label_61->setObjectName(QString::fromUtf8("label_61"));
        label_61->setGeometry(QRect(160, 80, 51, 31));
        label_61->setFrameShape(QFrame::StyledPanel);
        label_62 = new QLabel(page_4);
        label_62->setObjectName(QString::fromUtf8("label_62"));
        label_62->setGeometry(QRect(160, 230, 51, 31));
        label_62->setFrameShape(QFrame::StyledPanel);
        lineEdit_posS_Y = new QLineEdit(page_4);
        lineEdit_posS_Y->setObjectName(QString::fromUtf8("lineEdit_posS_Y"));
        lineEdit_posS_Y->setGeometry(QRect(60, 50, 101, 31));
        label_63 = new QLabel(page_4);
        label_63->setObjectName(QString::fromUtf8("label_63"));
        label_63->setGeometry(QRect(160, 20, 51, 31));
        label_63->setFrameShape(QFrame::StyledPanel);
        label_64 = new QLabel(page_4);
        label_64->setObjectName(QString::fromUtf8("label_64"));
        label_64->setGeometry(QRect(10, 20, 51, 31));
        label_64->setFrameShape(QFrame::StyledPanel);
        lineEdit_posS_A = new QLineEdit(page_4);
        lineEdit_posS_A->setObjectName(QString::fromUtf8("lineEdit_posS_A"));
        lineEdit_posS_A->setGeometry(QRect(60, 110, 101, 31));
        label_65 = new QLabel(page_4);
        label_65->setObjectName(QString::fromUtf8("label_65"));
        label_65->setGeometry(QRect(10, 50, 51, 31));
        label_65->setFrameShape(QFrame::StyledPanel);
        label_66 = new QLabel(page_4);
        label_66->setObjectName(QString::fromUtf8("label_66"));
        label_66->setGeometry(QRect(10, 170, 51, 31));
        label_66->setFrameShape(QFrame::StyledPanel);
        lineEdit_posS_C = new QLineEdit(page_4);
        lineEdit_posS_C->setObjectName(QString::fromUtf8("lineEdit_posS_C"));
        lineEdit_posS_C->setGeometry(QRect(60, 170, 101, 31));
        lineEdit_posS_Z = new QLineEdit(page_4);
        lineEdit_posS_Z->setObjectName(QString::fromUtf8("lineEdit_posS_Z"));
        lineEdit_posS_Z->setGeometry(QRect(60, 80, 101, 31));
        lineEdit_32 = new QLineEdit(page_4);
        lineEdit_32->setObjectName(QString::fromUtf8("lineEdit_32"));
        lineEdit_32->setGeometry(QRect(60, 230, 101, 31));
        lineEdit_posS_B = new QLineEdit(page_4);
        lineEdit_posS_B->setObjectName(QString::fromUtf8("lineEdit_posS_B"));
        lineEdit_posS_B->setGeometry(QRect(60, 140, 101, 31));
        label_67 = new QLabel(page_4);
        label_67->setObjectName(QString::fromUtf8("label_67"));
        label_67->setGeometry(QRect(10, 200, 51, 31));
        label_67->setFrameShape(QFrame::StyledPanel);
        label_68 = new QLabel(page_4);
        label_68->setObjectName(QString::fromUtf8("label_68"));
        label_68->setGeometry(QRect(10, 140, 51, 31));
        label_68->setFrameShape(QFrame::StyledPanel);
        label_69 = new QLabel(page_4);
        label_69->setObjectName(QString::fromUtf8("label_69"));
        label_69->setGeometry(QRect(160, 140, 51, 31));
        label_69->setFrameShape(QFrame::StyledPanel);
        stackedWidget_2->addWidget(page_4);
        pushButton_setpu_currentposition = new QPushButton(PositionSeriate);
        pushButton_setpu_currentposition->setObjectName(QString::fromUtf8("pushButton_setpu_currentposition"));
        pushButton_setpu_currentposition->setGeometry(QRect(210, 450, 101, 27));
        pushButton_setpu_currentposition->setFont(font1);
        pushButton_new_position = new QPushButton(PositionSeriate);
        pushButton_new_position->setObjectName(QString::fromUtf8("pushButton_new_position"));
        pushButton_new_position->setGeometry(QRect(390, 40, 99, 27));
        pushButton_new_position->setFont(font);
        pushButton_select_position = new QPushButton(PositionSeriate);
        pushButton_select_position->setObjectName(QString::fromUtf8("pushButton_select_position"));
        pushButton_select_position->setGeometry(QRect(290, 70, 99, 27));
        pushButton_select_position->setFont(font);

        retranslateUi(PositionSeriate);

        stackedWidget->setCurrentIndex(0);
        stackedWidget_2->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(PositionSeriate);
    } // setupUi

    void retranslateUi(QWidget *PositionSeriate)
    {
        PositionSeriate->setWindowTitle(QApplication::translate("PositionSeriate", "Form", 0, QApplication::UnicodeUTF8));
        label->setText(QApplication::translate("PositionSeriate", "\344\275\215\347\275\256\347\202\271\357\274\2101-999\357\274\211\357\274\232P", 0, QApplication::UnicodeUTF8));
        pushButton_posi_variate_data->setText(QApplication::translate("PositionSeriate", "\346\237\245\347\234\213\344\275\215\347\275\256\347\202\271", 0, QApplication::UnicodeUTF8));
        label_2->setText(QApplication::translate("PositionSeriate", "\344\275\215\347\275\256\347\202\271\345\235\220\346\240\207", 0, QApplication::UnicodeUTF8));
        label_3->setText(QApplication::translate("PositionSeriate", "\345\235\220\346\240\207\347\263\273\357\274\232", 0, QApplication::UnicodeUTF8));
        comboBox_po_co_select->clear();
        comboBox_po_co_select->insertItems(0, QStringList()
         << QApplication::translate("PositionSeriate", "\345\205\263\350\212\202\345\235\220\346\240\207\347\263\273", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("PositionSeriate", "\344\270\226\347\225\214\345\235\220\346\240\207\347\263\273", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("PositionSeriate", "\345\234\206\346\237\261\345\235\220\346\240\207\347\263\273", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("PositionSeriate", "\345\267\245\345\205\267\345\235\220\346\240\207\347\263\273", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("PositionSeriate", "\345\267\245\344\273\266\345\235\220\346\240\207\347\263\273", 0, QApplication::UnicodeUTF8)
        );
        label_4->setText(QApplication::translate("PositionSeriate", "J1", 0, QApplication::UnicodeUTF8));
        label_5->setText(QApplication::translate("PositionSeriate", "\345\272\246", 0, QApplication::UnicodeUTF8));
        label_6->setText(QApplication::translate("PositionSeriate", "\345\272\246", 0, QApplication::UnicodeUTF8));
        label_7->setText(QApplication::translate("PositionSeriate", "J2", 0, QApplication::UnicodeUTF8));
        label_8->setText(QApplication::translate("PositionSeriate", "J4", 0, QApplication::UnicodeUTF8));
        label_9->setText(QApplication::translate("PositionSeriate", "\345\272\246", 0, QApplication::UnicodeUTF8));
        label_10->setText(QApplication::translate("PositionSeriate", "J3", 0, QApplication::UnicodeUTF8));
        label_11->setText(QApplication::translate("PositionSeriate", "\345\272\246", 0, QApplication::UnicodeUTF8));
        label_12->setText(QApplication::translate("PositionSeriate", "J6", 0, QApplication::UnicodeUTF8));
        label_13->setText(QApplication::translate("PositionSeriate", "\345\272\246", 0, QApplication::UnicodeUTF8));
        label_14->setText(QApplication::translate("PositionSeriate", "J5", 0, QApplication::UnicodeUTF8));
        label_15->setText(QApplication::translate("PositionSeriate", "\345\272\246", 0, QApplication::UnicodeUTF8));
        label_16->setText(QApplication::translate("PositionSeriate", "J8", 0, QApplication::UnicodeUTF8));
        label_17->setText(QApplication::translate("PositionSeriate", "\345\272\246", 0, QApplication::UnicodeUTF8));
        label_18->setText(QApplication::translate("PositionSeriate", "J7", 0, QApplication::UnicodeUTF8));
        label_19->setText(QApplication::translate("PositionSeriate", "\345\272\246", 0, QApplication::UnicodeUTF8));
        label_38->setText(QApplication::translate("PositionSeriate", "Z", 0, QApplication::UnicodeUTF8));
        label_39->setText(QApplication::translate("PositionSeriate", "\346\257\253\347\261\263", 0, QApplication::UnicodeUTF8));
        label_40->setText(QApplication::translate("PositionSeriate", "\346\257\253\347\261\263", 0, QApplication::UnicodeUTF8));
        label_41->setText(QApplication::translate("PositionSeriate", "Ex2", 0, QApplication::UnicodeUTF8));
        label_42->setText(QApplication::translate("PositionSeriate", "A", 0, QApplication::UnicodeUTF8));
        label_43->setText(QApplication::translate("PositionSeriate", "\346\257\253\347\261\263", 0, QApplication::UnicodeUTF8));
        label_44->setText(QApplication::translate("PositionSeriate", "\346\257\253\347\261\263", 0, QApplication::UnicodeUTF8));
        label_45->setText(QApplication::translate("PositionSeriate", "\346\257\253\347\261\263", 0, QApplication::UnicodeUTF8));
        label_46->setText(QApplication::translate("PositionSeriate", "\346\257\253\347\261\263", 0, QApplication::UnicodeUTF8));
        label_47->setText(QApplication::translate("PositionSeriate", "\346\257\253\347\261\263", 0, QApplication::UnicodeUTF8));
        label_48->setText(QApplication::translate("PositionSeriate", "X", 0, QApplication::UnicodeUTF8));
        label_49->setText(QApplication::translate("PositionSeriate", "Y", 0, QApplication::UnicodeUTF8));
        label_50->setText(QApplication::translate("PositionSeriate", "C", 0, QApplication::UnicodeUTF8));
        label_51->setText(QApplication::translate("PositionSeriate", "Ex1", 0, QApplication::UnicodeUTF8));
        label_52->setText(QApplication::translate("PositionSeriate", "B", 0, QApplication::UnicodeUTF8));
        label_53->setText(QApplication::translate("PositionSeriate", "\346\257\253\347\261\263", 0, QApplication::UnicodeUTF8));
        label_20->setText(QApplication::translate("PositionSeriate", "\345\235\220\346\240\207\347\263\273\357\274\232", 0, QApplication::UnicodeUTF8));
        label_21->setText(QApplication::translate("PositionSeriate", "\345\275\223\345\211\215\346\234\272\345\231\250\344\272\272\345\235\220\346\240\207", 0, QApplication::UnicodeUTF8));
        comboBox_cu_co_select->clear();
        comboBox_cu_co_select->insertItems(0, QStringList()
         << QApplication::translate("PositionSeriate", "\345\205\263\350\212\202\345\235\220\346\240\207\347\263\273", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("PositionSeriate", "\344\270\226\347\225\214\345\235\220\346\240\207\347\263\273", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("PositionSeriate", "\345\234\206\346\237\261\345\235\220\346\240\207\347\263\273", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("PositionSeriate", "\345\267\245\345\205\267\345\235\220\346\240\207\347\263\273", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("PositionSeriate", "\345\267\245\344\273\266\345\235\220\346\240\207\347\263\273", 0, QApplication::UnicodeUTF8)
        );
        pushButton_pos_save->setText(QApplication::translate("PositionSeriate", "\344\277\235\345\255\230", 0, QApplication::UnicodeUTF8));
        pushButton_pos_close->setText(QApplication::translate("PositionSeriate", "\345\205\263\351\227\255", 0, QApplication::UnicodeUTF8));
        label_22->setText(QApplication::translate("PositionSeriate", "J1", 0, QApplication::UnicodeUTF8));
        label_23->setText(QApplication::translate("PositionSeriate", "\345\272\246", 0, QApplication::UnicodeUTF8));
        label_24->setText(QApplication::translate("PositionSeriate", "\345\272\246", 0, QApplication::UnicodeUTF8));
        label_25->setText(QApplication::translate("PositionSeriate", "J2", 0, QApplication::UnicodeUTF8));
        label_26->setText(QApplication::translate("PositionSeriate", "J4", 0, QApplication::UnicodeUTF8));
        label_27->setText(QApplication::translate("PositionSeriate", "\345\272\246", 0, QApplication::UnicodeUTF8));
        label_28->setText(QApplication::translate("PositionSeriate", "J3", 0, QApplication::UnicodeUTF8));
        label_29->setText(QApplication::translate("PositionSeriate", "\345\272\246", 0, QApplication::UnicodeUTF8));
        label_30->setText(QApplication::translate("PositionSeriate", "J6", 0, QApplication::UnicodeUTF8));
        label_31->setText(QApplication::translate("PositionSeriate", "\345\272\246", 0, QApplication::UnicodeUTF8));
        label_32->setText(QApplication::translate("PositionSeriate", "J5", 0, QApplication::UnicodeUTF8));
        label_33->setText(QApplication::translate("PositionSeriate", "\345\272\246", 0, QApplication::UnicodeUTF8));
        label_34->setText(QApplication::translate("PositionSeriate", "J8", 0, QApplication::UnicodeUTF8));
        label_35->setText(QApplication::translate("PositionSeriate", "\345\272\246", 0, QApplication::UnicodeUTF8));
        label_36->setText(QApplication::translate("PositionSeriate", "J7", 0, QApplication::UnicodeUTF8));
        label_37->setText(QApplication::translate("PositionSeriate", "\345\272\246", 0, QApplication::UnicodeUTF8));
        label_54->setText(QApplication::translate("PositionSeriate", "Z", 0, QApplication::UnicodeUTF8));
        label_55->setText(QApplication::translate("PositionSeriate", "\346\257\253\347\261\263", 0, QApplication::UnicodeUTF8));
        label_56->setText(QApplication::translate("PositionSeriate", "\346\257\253\347\261\263", 0, QApplication::UnicodeUTF8));
        label_57->setText(QApplication::translate("PositionSeriate", "Ex2", 0, QApplication::UnicodeUTF8));
        label_58->setText(QApplication::translate("PositionSeriate", "A", 0, QApplication::UnicodeUTF8));
        label_59->setText(QApplication::translate("PositionSeriate", "\346\257\253\347\261\263", 0, QApplication::UnicodeUTF8));
        label_60->setText(QApplication::translate("PositionSeriate", "\346\257\253\347\261\263", 0, QApplication::UnicodeUTF8));
        label_61->setText(QApplication::translate("PositionSeriate", "\346\257\253\347\261\263", 0, QApplication::UnicodeUTF8));
        label_62->setText(QApplication::translate("PositionSeriate", "\346\257\253\347\261\263", 0, QApplication::UnicodeUTF8));
        label_63->setText(QApplication::translate("PositionSeriate", "\346\257\253\347\261\263", 0, QApplication::UnicodeUTF8));
        label_64->setText(QApplication::translate("PositionSeriate", "X", 0, QApplication::UnicodeUTF8));
        label_65->setText(QApplication::translate("PositionSeriate", "Y", 0, QApplication::UnicodeUTF8));
        label_66->setText(QApplication::translate("PositionSeriate", "C", 0, QApplication::UnicodeUTF8));
        label_67->setText(QApplication::translate("PositionSeriate", "Ex1", 0, QApplication::UnicodeUTF8));
        label_68->setText(QApplication::translate("PositionSeriate", "B", 0, QApplication::UnicodeUTF8));
        label_69->setText(QApplication::translate("PositionSeriate", "\346\257\253\347\261\263", 0, QApplication::UnicodeUTF8));
        pushButton_setpu_currentposition->setText(QApplication::translate("PositionSeriate", "\350\256\276\344\270\272\345\275\223\345\211\215\344\275\215\347\275\256", 0, QApplication::UnicodeUTF8));
        pushButton_new_position->setText(QApplication::translate("PositionSeriate", "\346\226\260\345\273\272\344\275\215\347\275\256\347\202\271", 0, QApplication::UnicodeUTF8));
        pushButton_select_position->setText(QApplication::translate("PositionSeriate", "\345\210\240\351\231\244", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class PositionSeriate: public Ui_PositionSeriate {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_POSITIONSERIATE_H
