#ifndef XMLTAGNAME_H
#define XMLTAGNAME_H

#define XML_TAG_NAME_MOVJ               "movj"
#define XML_TAG_NAME_MOVL               "movl"
#define XML_TAG_NAME_MOVC               "movc"
#define XML_TAG_NAME_SPEED              "speed"
#define XML_TAG_NAME_POSITION           "positon"
#define XML_TAG_NAME_VJ                 "vj"
#define XML_TAG_NAME_PL                 "pl"
#define XML_TAG_NAME_UNTILL             "untill"
#define XML_TAG_NAME_IOSELECT           "ioselect"
#define XML_TAG_NAME_IONUMBER           "ionumber"
#define XML_TAG_NAME_IOPREPARE          "ioprepare"
#define XML_TAG_NAME_IOVALUE            "iovalue"
#define XML_TAG_NAME_IOIO               "ioio"
#define XML_TAG_NAME_ACC                "acc"
#define XML_TAG_NAME_DEC                "dec"
#define XML_TAG_NAME_NWAIT              "nwait"
#define XML_TAG_NAME_VL                 "vl"
#define XML_TAG_NAME_VR                 "vr"
#define XML_TAG_NAME_USR                "usrvalue"
#define XML_TAG_NAME_TOOL               "toolvalue"
#define XML_TAG_NAME_VSTYLE             "vstyle"
#define XML_TAG_NAME_VALUE              "value"
#define XML_TAG_NAME_DOUT               "DOUT"
#define XML_TAG_NAME_BYTENUMBER         "byteNumber"
#define XML_TAG_NAME_INPUTADDRESS       "inputAddress"
#define XML_TAG_NAME_DIN                "DIN"
#define XML_TAG_NAME_DOADDRESS          "doAddress"
#define XML_TAG_NAME_DOVALUE            "dovalue"
#define XML_TAG_NAME_PAUSE              "PAUSE"
#define XML_TAG_NAME_IF                 "IF"
#define XML_TAG_NAME_VARTYPE            "varType"
#define XML_TAG_NAME_VARADDRESS         "varAddress"
#define XML_TAG_NAME_COMPARESIGN        "compareSign"
#define XML_TAG_NAME_COMPAREVALUE       "compareValue"
#define XML_TAG_NAME_TIMER              "TIMER"
#define XML_TAG_NAME_T                  "T"
#define XML_TAG_NAME_LABEL              "LABEL"
#define XML_TAG_NAME_NUMBER             "number"
#define XML_TAG_NAME_JUMP               "JUMP"
#define XML_TAG_NAME_LABELNUMBER        "LabelNumber"
#define XML_TAG_NAME_CALL               "CALL"
#define XML_TAG_NAME_FILENAME           "fileName"
#define XML_TAG_NAME_RET                "RET"
#define XML_TAG_NAME_END                "END"
#define XML_TAG_NAME_NOP                "NOP"
#define XML_TAG_NAME_JOINT              "Join"
#define XML_TAG_NAME_WORLD              "World"
#define XML_TAG_NAME_CYLINDER           "Cylindrical"
#define XML_TAG_NAME_FRAME_TOOL         "Tool"
#define XML_TAG_NAME_FRAME_USR          "Workpiece"
#define XML_TAG_NAME_IO_TYPE_B          "B"
#define XML_TAG_NAME_IO_TYPE_INT        "INT"
#define XML_TAG_NAME_IO_VALUE_ON        "ON"
#define XML_TAG_NAME_IO_VALUE_OFF       "OFF"
#define XML_TAG_NAME_SPEED_VJ           "VJ"
#define XML_TAG_NAME_SPEED_VL           "VL"
#define XML_TAG_NAME_SPEED_VR           "VR"




#endif // XMLTAGNAME_H
