######################################################################
# Automatically generated by qmake (3.0) Fri Dec 15 09:10:44 2017
######################################################################

TEMPLATE = app
TARGET = src
INCLUDEPATH += .

# Input
HEADERS += axis.h \
           commandinput.h \
           commandlist.h \
           configdialog.h \
           include.h \
           keypad.h \
           mainwindow.h \
           movecommand.h \
           newfilename.h \
           page2.h \
           positionseriate.h \
           robotoriginpointlocation.h \
           simulationkeypad.h \
           specialwork.h \
           speedadjust.h \
           typedef.h \
           codeeditor/codeeditor.h \
           deps/ui_axis.h \
           deps/ui_commandinput.h \
           deps/ui_commandlist.h \
           deps/ui_dialog.h \
           deps/ui_keypad.h \
           deps/ui_mainwindow.h \
           deps/ui_movecommand.h \
           deps/ui_newfilename.h \
           deps/ui_page1.h \
           deps/ui_page2.h \
           deps/ui_positionseriate.h \
           deps/ui_robotoriginpointlocation.h \
           deps/ui_simulationkeypad.h \
           deps/ui_specialwork.h \
           deps/ui_speedadjust.h \
           usr_motion_api/usr_motion_api.h \
           xml_cancle/xmlcancle.h
FORMS += axis.ui \
         commandinput.ui \
         commandlist.ui \
         dialog.ui \
         keypad.ui \
         mainwindow.ui \
         movecommand.ui \
         newfilename.ui \
         page1.ui \
         page2.ui \
         positionseriate.ui \
         robotoriginpointlocation.ui \
         simulationkeypad.ui \
         specialwork.ui \
         speedadjust.ui
SOURCES += axis.cpp \
           commandinput.cpp \
           commandlist.cpp \
           configdialog.cpp \
           keypad.cpp \
           main.cpp \
           mainwindow.cpp \
           movecommand.cpp \
           newfilename.cpp \
           page2.cpp \
           positionseriate.cpp \
           robotoriginpointlocation.cpp \
           simulationkeypad.cpp \
           specialwork.cpp \
           speedadjust.cpp \
           codeeditor/codeeditor.cpp \
           deps/qrc_resource.cpp \
           usr_motion_api/usr_motion_api.c \
           xml_cancle/xmlcancle.cpp
RESOURCES += resource.qrc
